export const LOGGED_IN_STATE_CHANGED = 'LOGGED_IN_STATE_CHANGED';
export const LOG_IN_SUBMIT = 'LOG_IN_SUBMIT';
export const FRIEND_LIST_UPDATE = 'FRIEND_LIST_UPDATE';
export const POPUP_OPEN = 'POPUP_OPEN';